{% set name = "osprofiler" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbd8a336644d801105c5b5bbc004af168e1b192578037651b611a7c5abdc7bd4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - osprofiler = osprofiler.cmd.shell:main

requirements:
  host:
    - pbr >=2.0
    - pip
    - python
  run:
    - python
    - netaddr >=0.7.18
    - oslo.concurrency >=3.26.0
    - oslo.serialization >=2.18.0
    - oslo.utils >=3.33.0
    - prettytable >=0.7.2
    - requests >=2.14.2
    - webob >=1.7.1
    - importlib_metadata >=1.7.0  # [py<38]

test:
  imports:
    - osprofiler
  commands:
    - osprofiler -h

about:
  home: https://docs.openstack.org/osprofiler/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: OpenStack Profiler Library

extra:
  recipe-maintainers:
    - tschoonj
