{% set name = "osprofiler" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b745b6967941cacb79d26555b5c34ca2ac53bbdf862788c1333d64f0cd4f554f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - osprofiler = osprofiler.cmd.shell:main

requirements:
  host:
    - pbr >=2.0
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - netaddr >=0.7.18
    - oslo.concurrency >=3.26.0
    - oslo.serialization >=2.18.0
    - oslo.utils >=3.33.0
    - prettytable >=0.7.2
    - requests >=2.14.2
    - six >=1.10.0
    - webob >=1.7.1

test:
  imports:
    - osprofiler
  commands:
    - osprofiler -h

about:
  home: https://docs.openstack.org/osprofiler/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: OpenStack Profiler Library

extra:
  recipe-maintainers:
    - tschoonj
